# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "20"
  commands:
    - npm ci
    - RTD_BASE_PATH="/${READTHEDOCS_LANGUAGE:-en}/${READTHEDOCS_VERSION:-latest}" npm run build
    - mkdir -p _readthedocs/html
    - cp -r out/* _readthedocs/html/
